begin;

create extension if not exists pgtap with schema extensions;

select plan(244);

-- Schema and immutable/versioned model.
select has_table('erp','stage7_commands','Stage 7 command ledger exists');
select has_table('erp','pc_compatibility_specs','PC compatibility specs exist');
select has_table('erp','pc_compatibility_spec_versions','PC spec versions exist');
select has_table('erp','pc_compatibility_rule_sets','PC rule sets exist');
select has_table('erp','pc_compatibility_rule_set_versions','PC rule-set versions exist');
select has_table('erp','pc_compatibility_rules','Versioned PC rules exist');
select has_table('erp','pc_test_templates','PC test templates exist');
select has_table('erp','pc_test_template_versions','PC test versions exist');
select has_table('erp','pc_build_projects','PC projects exist');
select has_table('erp','pc_build_state_events','PC state facts exist');
select has_table('erp','pc_build_revisions','PC revisions exist');
select has_table('erp','pc_build_components','Immutable PC components exist');
select has_table('erp','pc_compatibility_runs','Compatibility runs exist');
select has_table('erp','pc_compatibility_results','Compatibility results exist');
select has_table('erp','pc_build_reservations','PC reservation bridges exist');
select has_table('erp','pc_test_runs','PC test runs exist');
select has_table('erp','pc_test_results','PC test results exist');
select has_table('erp','pc_build_completions','PC completions exist');
select has_table('erp','pc_component_lineage','PC component lineage exists');
select has_table('erp','trade_ins','Trade-in intake exists');
select has_table('erp','trade_in_provenance_declarations','Provenance declarations exist');
select has_table('erp','trade_in_provenance_evidence','Private provenance evidence exists');
select has_table('erp','trade_in_provenance_reviews','Provenance reviews exist');
select has_table('erp','trade_in_imei_requests','IMEI requests exist');
select has_table('erp','trade_in_imei_results','IMEI results exist');
select has_table('erp','trade_in_evaluations','Versioned evaluations exist');
select has_table('erp','trade_in_evaluation_reviews','Evaluation reviews exist');
select has_table('erp','trade_in_refurbishments','Refurbishment links and costs exist');
select has_table('erp','trade_in_releases','Trade-in releases exist');
select has_table('erp','trade_in_sale_payment_events','Trade-in payment facts exist');

select has_column('erp','stage7_commands','request_hash','Commands retain request identity');
select has_column('erp','pc_build_revisions','supersedes_revision_id','PC revisions retain ancestry');
select has_column('erp','pc_build_revisions','spec_version_id','PC revisions pin specs');
select has_column('erp','pc_build_revisions','rule_set_version_id','PC revisions pin rules');
select has_column('erp','pc_build_components','inventory_unit_id','PC components retain unit identity');
select has_column('erp','pc_build_components','specification_snapshot','PC component specs are frozen');
select has_column('erp','pc_build_components','unit_cost_snapshot','PC component costs are frozen');
select has_column('erp','pc_build_components','serial_snapshot','PC component serials are frozen');
select has_column('erp','pc_build_components','warranty_snapshot','PC component warranties are frozen');
select has_column('erp','pc_compatibility_runs','run_sequence','Compatibility chronology is monotonic');
select has_column('erp','pc_test_runs','run_sequence','PC test chronology is monotonic');
select has_column('erp','pc_build_completions','stock_document_id','Completion retains fulfillment');
select has_column('erp','pc_build_completions','equipment_id','Completion retains resulting equipment');
select has_column('erp','pc_component_lineage','serial_snapshot','Lineage retains serial');
select has_column('erp','pc_component_lineage','unit_cost_snapshot','Lineage retains cost');
select has_column('erp','pc_component_lineage','warranty_snapshot','Lineage retains warranty');
select has_column('erp','trade_ins','inventory_unit_id','Trade-in retains quarantined unit');
select has_column('erp','trade_ins','quarantine_location_id','Trade-in retains quarantine location');
select has_column('erp','trade_in_imei_requests','imei_hmac','IMEI request identity is keyed');
select has_column('erp','trade_in_imei_requests','imei_ciphertext','Provider IMEI is encrypted');
select has_column('erp','trade_in_imei_results','request_hash','Provider result retry identity is strong');
select has_column('erp','trade_in_evaluations','supersedes_evaluation_id','Evaluation ancestry is retained');
select has_column('erp','trade_in_refurbishments','repair_order_id','Refurbishment can link a repair');
select has_column('erp','trade_in_refurbishments','actual_cost_base','Refurbishment captures cost');
select has_column('erp','trade_in_releases','total_cost_base','Release freezes exact total cost');
select has_column('erp','trade_in_sale_payment_events','reverses_event_id','Trade-in payments retain reversal lineage');

-- RPC surface and preservation of prior public contracts.
select has_function('erp','create_pc_build_project',array['uuid','uuid','text','text','text','text'],'PC project command exists');
select has_function('erp','create_pc_build_revision',array['uuid','uuid','uuid','jsonb','jsonb','text','text'],'PC revision command exists');
select has_function('erp','record_pc_compatibility_run',array['uuid','text','text'],'Compatibility command exists');
select has_function('erp','reserve_pc_build_components',array['uuid','uuid','timestamp with time zone','jsonb','text','text'],'PC reservation wrapper exists');
select has_function('erp','record_pc_test_run',array['uuid','uuid','jsonb','text','text'],'PC test command exists');
select has_function('erp','complete_pc_build',array['uuid','uuid','uuid','text','jsonb','text','text'],'PC completion command exists');
select has_function('erp','create_trade_in',array['uuid','uuid','uuid','uuid','text','text','text','text','jsonb','numeric','text','text'],'Trade-in intake command exists');
select has_function('erp','review_trade_in_provenance',array['uuid','erp.trade_in_review_decision','text'],'Provenance review command exists');
select has_function('erp','request_trade_in_imei_check',array['uuid','text','text','text'],'IMEI request command exists');
select has_function('erp','get_trade_in_imei_provider_request',array['uuid'],'Provider dispatch read exists');
select has_function('erp','record_trade_in_imei_provider_result',array['uuid','erp.imei_check_status','text','jsonb','text'],'Provider result command exists');
select has_function('erp','record_trade_in_imei_manual_fallback',array['uuid','erp.imei_check_status','jsonb','text','text'],'Manual fallback command exists');
select has_function('erp','create_trade_in_evaluation',array['uuid','jsonb','numeric','numeric','text','text'],'Evaluation command exists');
select has_function('erp','review_trade_in_evaluation',array['uuid','erp.trade_in_review_decision','text'],'Evaluation review command exists');
select has_function('erp','record_trade_in_refurbishment',array['uuid','uuid','text','numeric','boolean','text','text'],'Refurbishment cost command exists');
select has_function('erp','release_trade_in_to_stock',array['uuid','uuid','text','text'],'Trade-in release command exists');
select has_function('erp','apply_trade_in_sale_payment',array['uuid','uuid','numeric','text','text'],'Trade-in payment command exists');
select has_function('erp','reverse_trade_in_sale_payment',array['uuid','text','text'],'Trade-in payment reversal exists');
select has_function('erp','get_pc_build_costs',array['uuid'],'Audited PC cost RPC exists');
select has_function('erp','get_trade_in_costs',array['uuid'],'Audited trade-in cost RPC exists');
select has_function('erp','assert_pc_project_mutable',array['uuid','uuid'],'PC project lock and terminal guard exists');
select has_function('erp','post_stock_document',array['erp.stock_document_kind','uuid','text','text','jsonb','boolean','text','uuid'],'Stock signature is preserved');
select has_function('erp','reverse_stock_document',array['uuid','text','text'],'Stock reversal signature is preserved');
select has_function('erp','fulfill_stock_reservation',array['uuid','text','text'],'Fulfillment signature is preserved');
select has_function('erp','create_stock_reservation',array['uuid','text','text','uuid','timestamp with time zone','jsonb'],'Reservation signature is preserved');
select has_function('erp','record_sale_payment',array['uuid','uuid','uuid','numeric','text','text','text'],'Sale payment signature is preserved');
select has_function('erp','reverse_sale_payment',array['uuid','text','text','uuid'],'Sale payment reversal signature is preserved');
select has_function('erp','create_customer_equipment',array['uuid','uuid','uuid','uuid','text','text','text','text','text','text','text'],'Equipment signature is preserved');
select has_function('erp','create_repair_order',array['uuid','uuid','uuid','jsonb','text','text','text','text','text','text'],'Repair order signature is preserved');
select has_function('public','get_repair_tracking',array['text'],'Public repair tracking signature is preserved');
select has_function('public','respond_repair_quote',array['text','text','text'],'Public quote signature is preserved');

-- Composite integrity, append-only facts, JSON bounds and finite numerics.
select ok(exists(select 1 from pg_constraint where conrelid='erp.pc_build_projects'::regclass and conname='pc_projects_id_org_branch_unique'),'PC project owner tuple is unique');
select ok(exists(select 1 from pg_constraint where conrelid='erp.pc_build_revisions'::regclass and conname='pc_revisions_owner_unique'),'PC revision owner tuple is unique');
select ok(exists(select 1 from pg_constraint where conrelid='erp.pc_build_revisions'::regclass and conname='pc_revisions_supersedes_fk'),'Revision ancestry is same-owner constrained');
select ok(exists(select 1 from pg_constraint where conrelid='erp.pc_build_components'::regclass and conname='pc_components_line_unique'),'Component lines are unique');
select ok(exists(select 1 from pg_constraint where conrelid='erp.pc_build_components'::regclass and conname='pc_components_slot_unique'),'Component slots are unique');
select ok(exists(select 1 from pg_constraint where conrelid='erp.pc_build_reservations'::regclass and conname='pc_reservations_revision_fk'),'PC reservations use composite revision ownership');
select ok(exists(select 1 from pg_constraint where conrelid='erp.pc_build_completions'::regclass and conname='pc_completions_revision_fk'),'Completion uses composite revision ownership');
select ok(exists(select 1 from pg_constraint where conrelid='erp.pc_component_lineage'::regclass and conname='pc_lineage_component_fk'),'Lineage references immutable component');
select ok(exists(select 1 from pg_constraint where conrelid='erp.trade_ins'::regclass and conname='trade_ins_id_org_branch_unique'),'Trade-in owner tuple is unique');
select ok(exists(select 1 from pg_constraint where conrelid='erp.trade_ins'::regclass and conname='trade_ins_location_fk'),'Quarantine location is branch-composite constrained');
select ok(exists(select 1 from pg_constraint where conrelid='erp.trade_in_evaluations'::regclass and conname='trade_evaluations_owner_unique'),'Evaluation owner tuple is unique');
select ok(exists(select 1 from pg_constraint where conrelid='erp.trade_in_evaluations'::regclass and conname='trade_evaluations_supersedes_fk'),'Evaluation ancestry is same-trade constrained');
select ok(exists(select 1 from pg_constraint where conrelid='erp.trade_in_releases'::regclass and conname='trade_releases_eval_fk'),'Release evaluation is same-trade constrained');
select ok(exists(select 1 from pg_constraint where conrelid='erp.trade_in_releases'::regclass and conname='trade_releases_location_fk'),'Release location is same-branch constrained');
select ok(exists(select 1 from pg_constraint where conrelid='erp.trade_in_sale_payment_events'::regclass and conname='trade_payment_reverses_fk'),'Payment reversal is same-tenant constrained');
select ok(exists(select 1 from pg_constraint where conrelid='erp.trade_in_sale_payment_events'::regclass and conname='trade_payment_reversal_unique'),'Payment reversal event can be recorded only once');
select ok(exists(select 1 from pg_constraint where conrelid='erp.trade_in_imei_results'::regclass and conname='trade_imei_results_request_owner_fk'),'IMEI results retain exact request ownership');
select ok(exists(select 1 from pg_indexes where schemaname='erp' and tablename='trade_in_imei_results' and indexname='trade_imei_provider_result_once'),'Each IMEI request has at most one provider result');
select ok(exists(select 1 from pg_indexes where schemaname='erp' and tablename='trade_in_refurbishments' and indexname='trade_refurbishment_repair_once'),'A delivered repair cost can be captured by only one trade-in');
select ok((select pg_get_constraintdef(oid) like '%pg_column_size(configuration) <= 262144%' from pg_constraint where conrelid='erp.pc_build_revisions'::regclass and conname='pc_build_revisions_configuration_check'),'Revision JSON is bounded');
select ok((select pg_get_constraintdef(oid) like '%pg_column_size(specification_snapshot) <= 65536%' from pg_constraint where conrelid='erp.pc_build_components'::regclass and conname='pc_build_components_specification_snapshot_check'),'Component spec JSON is bounded');
select ok((select pg_get_constraintdef(oid) like '%unit_cost_snapshot <>%NaN%' from pg_constraint where conrelid='erp.pc_build_components'::regclass and conname='pc_build_components_unit_cost_snapshot_check'),'Component costs reject NaN');
select ok((select pg_get_constraintdef(oid) like '%pg_column_size(evidence) <= 262144%' from pg_constraint where conrelid='erp.trade_in_imei_results'::regclass and conname='trade_in_imei_results_evidence_check'),'IMEI evidence is bounded');
select ok((select pg_get_constraintdef(oid) like '%appraised_value_base <>%NaN%' from pg_constraint where conrelid='erp.trade_in_evaluations'::regclass and conname='trade_in_evaluations_appraised_value_base_check'),'Evaluation values reject NaN');
select ok((select pg_get_constraintdef(oid) like '%actual_cost_base <>%NaN%' from pg_constraint where conrelid='erp.trade_in_refurbishments'::regclass and conname='trade_in_refurbishments_actual_cost_base_check'),'Refurbishment costs reject NaN');
select ok((select coalesce(pg_get_constraintdef(oid),'') like '%accepted_value_base%' and coalesce(pg_get_constraintdef(oid),'') like '%refurbishment_cost_base%' from pg_constraint where conrelid='erp.trade_in_releases'::regclass and conname='trade_in_releases_check'),'Release total cost reconciles exactly');
select ok(exists(select 1 from pg_trigger where tgrelid='erp.pc_build_components'::regclass and tgname='pc_build_components_immutable'),'PC components are append-only');
select ok(exists(select 1 from pg_trigger where tgrelid='erp.pc_component_lineage'::regclass and tgname='pc_component_lineage_immutable'),'Component lineage is append-only');
select ok(exists(select 1 from pg_trigger where tgrelid='erp.trade_in_provenance_reviews'::regclass and tgname='trade_in_provenance_reviews_immutable'),'Provenance reviews are append-only');
select ok(exists(select 1 from pg_trigger where tgrelid='erp.trade_in_imei_results'::regclass and tgname='trade_in_imei_results_immutable'),'IMEI results are append-only');
select ok(exists(select 1 from pg_trigger where tgrelid='erp.trade_in_evaluations'::regclass and tgname='trade_in_evaluations_immutable'),'Evaluations are append-only');
select ok(exists(select 1 from pg_trigger where tgrelid='erp.trade_in_releases'::regclass and tgname='trade_in_releases_immutable'),'Releases are append-only');
select ok(exists(select 1 from pg_trigger where tgrelid='erp.trade_in_sale_payment_events'::regclass and tgname='trade_in_sale_payment_events_immutable'),'Payment links are append-only');
select ok(exists(select 1 from pg_trigger where tgrelid='erp.pc_compatibility_spec_versions'::regclass and tgname='pc_spec_versions_immutable'),'PC specs are immutable');
select ok(exists(select 1 from pg_trigger where tgrelid='erp.pc_compatibility_rules'::regclass and tgname='pc_rules_immutable'),'PC rules are immutable');
select ok(exists(select 1 from pg_trigger where tgrelid='erp.pc_test_template_versions'::regclass and tgname='pc_test_versions_immutable'),'PC tests are immutable');

-- RLS and least privilege.
select ok((select relrowsecurity from pg_class where oid='erp.stage7_commands'::regclass),'Commands enforce RLS');
select ok((select relrowsecurity from pg_class where oid='erp.pc_build_projects'::regclass),'PC projects enforce RLS');
select ok((select relrowsecurity from pg_class where oid='erp.pc_build_revisions'::regclass),'PC revisions enforce RLS');
select ok((select relrowsecurity from pg_class where oid='erp.pc_build_components'::regclass),'PC components enforce RLS');
select ok((select relrowsecurity from pg_class where oid='erp.pc_compatibility_runs'::regclass),'Compatibility runs enforce RLS');
select ok((select relrowsecurity from pg_class where oid='erp.pc_compatibility_results'::regclass),'Compatibility results enforce RLS');
select ok((select relrowsecurity from pg_class where oid='erp.pc_build_reservations'::regclass),'PC reservations enforce RLS');
select ok((select relrowsecurity from pg_class where oid='erp.pc_test_runs'::regclass),'PC tests enforce RLS');
select ok((select relrowsecurity from pg_class where oid='erp.pc_build_completions'::regclass),'PC completions enforce RLS');
select ok((select relrowsecurity from pg_class where oid='erp.pc_component_lineage'::regclass),'Lineage enforces RLS');
select ok((select relrowsecurity from pg_class where oid='erp.trade_ins'::regclass),'Trade-ins enforce RLS');
select ok((select relrowsecurity from pg_class where oid='erp.trade_in_provenance_declarations'::regclass),'Declarations enforce RLS');
select ok((select relrowsecurity from pg_class where oid='erp.trade_in_provenance_evidence'::regclass),'Evidence enforces RLS');
select ok((select relrowsecurity from pg_class where oid='erp.trade_in_provenance_reviews'::regclass),'Provenance reviews enforce RLS');
select ok((select relrowsecurity from pg_class where oid='erp.trade_in_imei_requests'::regclass),'IMEI requests enforce RLS');
select ok((select relrowsecurity from pg_class where oid='erp.trade_in_imei_results'::regclass),'IMEI results enforce RLS');
select ok((select relrowsecurity from pg_class where oid='erp.trade_in_evaluations'::regclass),'Evaluations enforce RLS');
select ok((select relrowsecurity from pg_class where oid='erp.trade_in_evaluation_reviews'::regclass),'Evaluation reviews enforce RLS');
select ok((select relrowsecurity from pg_class where oid='erp.trade_in_refurbishments'::regclass),'Refurbishments enforce RLS');
select ok((select relrowsecurity from pg_class where oid='erp.trade_in_releases'::regclass),'Releases enforce RLS');
select ok((select relrowsecurity from pg_class where oid='erp.trade_in_sale_payment_events'::regclass),'Trade-in payments enforce RLS');
select ok((select qual like '%organization_id = %current_organization_id()%has_permission(''pc_builds.view''%branch_id%' from pg_policies where schemaname='erp' and tablename='pc_build_projects' and policyname='pc_projects_select'),'PC project RLS is tenant and branch scoped');
select ok((select qual like '%organization_id = %current_organization_id()%has_permission(''trade_ins.view''%branch_id%' from pg_policies where schemaname='erp' and tablename='trade_ins' and policyname='trade_ins_select'),'Trade-in RLS is tenant and branch scoped');
select ok((select qual like '%pc_build_components.organization_id%has_permission(''pc_builds.view''%' from pg_policies where schemaname='erp' and tablename='pc_build_components' and policyname='pc_components_select'),'Component child RLS resolves its owning branch');
select is((select count(*) from pg_policies where schemaname='erp' and tablename='trade_in_imei_results' and cmd in('INSERT','ALL')),0::bigint,'No client policy permits provider-result insertion');
select is(has_table_privilege('anon','erp.trade_ins','SELECT'),false,'Anon cannot read trade-ins');
select is(has_table_privilege('anon','erp.pc_build_projects','SELECT'),false,'Anon cannot read PC projects');
select is(has_table_privilege('authenticated','erp.trade_ins','INSERT'),false,'Authenticated cannot insert trade-ins directly');
select is(has_table_privilege('service_role','erp.trade_ins','INSERT'),false,'Service role cannot insert trade-ins directly');
select is(has_table_privilege('authenticated','erp.pc_build_components','INSERT'),false,'Authenticated cannot insert components directly');
select is(has_table_privilege('authenticated','erp.trade_in_imei_requests','SELECT'),false,'Authenticated cannot read encrypted IMEI requests');
select is(has_table_privilege('service_role','erp.trade_in_imei_requests','SELECT'),false,'Service role cannot bypass audited IMEI request RPC');
select is(has_column_privilege('authenticated','erp.pc_build_components','unit_cost_snapshot','SELECT'),false,'General PC view cannot read component costs');
select is(has_column_privilege('authenticated','erp.pc_build_components','serial_snapshot','SELECT'),false,'General PC view cannot read component serials');
select is(has_column_privilege('authenticated','erp.pc_component_lineage','unit_cost_snapshot','SELECT'),false,'General PC view cannot read lineage costs');
select is(has_column_privilege('authenticated','erp.pc_component_lineage','serial_snapshot','SELECT'),false,'General PC view cannot read lineage serials');
select is(has_column_privilege('authenticated','erp.trade_in_provenance_evidence','private_object_path','SELECT'),false,'Evidence paths are private');
select is(has_column_privilege('authenticated','erp.trade_in_imei_results','provider_reference','SELECT'),false,'Provider references are private');
select is(has_column_privilege('authenticated','erp.trade_in_imei_results','evidence','SELECT'),false,'Provider evidence is private');
select is(has_column_privilege('authenticated','erp.trade_in_evaluations','appraised_value_base','SELECT'),false,'Appraised values require the cost RPC');
select is(has_column_privilege('authenticated','erp.trade_in_refurbishments','actual_cost_base','SELECT'),false,'Refurbishment costs require the cost RPC');
select is(has_function_privilege('anon','erp.create_trade_in(uuid,uuid,uuid,uuid,text,text,text,text,jsonb,numeric,text,text)','EXECUTE'),false,'Anon cannot create trade-ins');
select is(has_function_privilege('anon','erp.create_pc_build_project(uuid,uuid,text,text,text,text)','EXECUTE'),false,'Anon cannot create PC projects');
select is(has_function_privilege('authenticated','erp.get_trade_in_imei_provider_request(uuid)','EXECUTE'),false,'Authenticated cannot decrypt provider requests');
select is(has_function_privilege('service_role','erp.get_trade_in_imei_provider_request(uuid)','EXECUTE'),true,'Service role can use audited provider request RPC');
select is(has_function_privilege('authenticated','erp.record_trade_in_imei_provider_result(uuid,erp.imei_check_status,text,jsonb,text)','EXECUTE'),false,'Authenticated cannot forge provider results');
select is(has_function_privilege('service_role','erp.record_trade_in_imei_provider_result(uuid,erp.imei_check_status,text,jsonb,text)','EXECUTE'),true,'Service role alone records provider results');
select is(has_function_privilege('service_role','erp.create_trade_in(uuid,uuid,uuid,uuid,text,text,text,text,jsonb,numeric,text,text)','EXECUTE'),false,'Service role cannot use staff intake command');
select is(has_function_privilege('authenticated','erp.claim_stage7_command(text,uuid,uuid,text,jsonb)','EXECUTE'),false,'Command core is private');
select is(has_function_privilege('authenticated','erp.post_stock_document_stage7_core(erp.stock_document_kind,uuid,text,text,jsonb,boolean,text,uuid)','EXECUTE'),false,'Quarantine bypass core is private');
select is(has_function_privilege('authenticated','erp.reverse_stock_document_stage7_core(uuid,text,text)','EXECUTE'),false,'Trade-in stock reversal core is private');
select is(has_function_privilege('service_role','erp.reverse_stock_document_stage7_core(uuid,text,text)','EXECUTE'),false,'Service role cannot bypass trade-in stock reversal');
select is(has_function_privilege('authenticated','erp.reverse_sale_payment_stage7_core(uuid,text,text,uuid)','EXECUTE'),false,'Trade-in payment reversal core is private');
select is(has_function_privilege('service_role','erp.reverse_sale_payment_stage7_core(uuid,text,text,uuid)','EXECUTE'),false,'Service role cannot bypass trade-in payment reversal');
select is(has_function_privilege('authenticated','erp.reverse_stock_document(uuid,text,text)','EXECUTE'),true,'Authenticated users retain the checked stock reversal contract');
select is(has_function_privilege('authenticated','erp.reverse_sale_payment(uuid,text,text,uuid)','EXECUTE'),true,'Authenticated users retain the checked payment reversal contract');

-- Static behavioral contract: locks, exactness, gates, redaction and wrappers.
create function pg_temp.normalized_functiondef(target regprocedure) returns text language sql stable as $$
  select lower(regexp_replace(pg_get_functiondef(target),'[[:space:]]+','','g'))
$$;
select ok(pg_temp.normalized_functiondef('erp.create_pc_build_revision(uuid,uuid,uuid,jsonb,jsonb,text,text)') like '%inventory_cost_balances%','Quantity component cost uses WAC');
select ok(pg_temp.normalized_functiondef('erp.create_pc_build_revision(uuid,uuid,uuid,jsonb,jsonb,text,text)') like '%serialized_acquisition_costs%','Serialized component cost uses specific cost');
select ok(pg_temp.normalized_functiondef('erp.create_pc_build_revision(uuid,uuid,uuid,jsonb,jsonb,text,text)') like '%specification_snapshot%warranty_snapshot%','Revision freezes specs and warranty');
select ok(pg_temp.normalized_functiondef('erp.record_pc_compatibility_run(uuid,text,text)') like '%required_slots%','Compatibility checks required slots');
select ok(pg_temp.normalized_functiondef('erp.record_pc_compatibility_run(uuid,text,text)') like '%pc_compatibility_rules%','Compatibility uses pinned rules');
select ok(pg_temp.normalized_functiondef('erp.record_pc_compatibility_run(uuid,text,text)') like '%matchedisnottrue%','Missing compatibility attributes cannot preserve a passing run');
select ok(pg_temp.normalized_functiondef('erp.reserve_pc_build_components(uuid,uuid,timestamptz,jsonb,text,text)') like '%create_stock_reservation%''pc_build''%','PC reservation uses existing source wrapper');
select ok(pg_temp.normalized_functiondef('erp.reserve_pc_build_components(uuid,uuid,timestamptz,jsonb,text,text)') like '%reservationmustexactlymatchrevisioncomponents%','PC reservation is an exact multiset');
select ok(pg_temp.normalized_functiondef('erp.assert_pc_project_mutable(uuid,uuid)') like '%pcprojectisterminal%','PC project mutation is terminal-state guarded');
select ok(pg_temp.normalized_functiondef('erp.record_pc_test_run(uuid,uuid,jsonb,text,text)') like '%pc_builds.final_test_template_version%','PC tests use the configured final template');
select ok(pg_temp.normalized_functiondef('erp.record_pc_test_run(uuid,uuid,jsonb,text,text)') like '%activecomponentreservationisrequired%','PC tests require an active reservation');
select ok(pg_temp.normalized_functiondef('erp.complete_pc_build(uuid,uuid,uuid,text,jsonb,text,text)') like '%fulfill_stock_reservation%','Completion uses cost-integrated fulfillment');
select ok(pg_temp.normalized_functiondef('erp.complete_pc_build(uuid,uuid,uuid,text,jsonb,text,text)') like '%result<>''pass''%','Completion requires passing latest tests');
select ok(pg_temp.normalized_functiondef('erp.complete_pc_build(uuid,uuid,uuid,text,jsonb,text,text)') like '%currentcompletepassingpctest%','Completion requires the current complete final test');
select ok(pg_temp.normalized_functiondef('erp.complete_pc_build(uuid,uuid,uuid,text,jsonb,text,text)') like '%stock_cost_movements%','Completion sources lineage from fulfillment cost facts');
select ok(pg_temp.normalized_functiondef('erp.complete_pc_build(uuid,uuid,uuid,text,jsonb,text,text)') like '%fulfillmentcostlineagedoesnotexactlymatch%','Completion requires exact component lineage');
select ok(pg_temp.normalized_functiondef('erp.complete_pc_build(uuid,uuid,uuid,text,jsonb,text,text)') like '%extensions.hmac%serial_hmac%','Build serial command identity is keyed');
select ok(pg_temp.normalized_functiondef('erp.complete_pc_build(uuid,uuid,uuid,text,jsonb,text,text)') like '%orderbykey_version%','Build serial retry supports key rotation');
select ok(pg_temp.normalized_functiondef('erp.create_trade_in(uuid,uuid,uuid,uuid,text,text,text,text,jsonb,numeric,text,text)') like '%extensions.hmac%imei_hmac%','Trade-in identifier command identity is keyed');
select ok(pg_temp.normalized_functiondef('erp.create_trade_in(uuid,uuid,uuid,uuid,text,text,text,text,jsonb,numeric,text,text)') like '%''quarantine''%','Trade-in unit starts quarantined');
select ok(pg_temp.normalized_functiondef('erp.create_trade_in(uuid,uuid,uuid,uuid,text,text,text,text,jsonb,numeric,text,text)') like '%trade_in_provenance_declarations%trade_in_provenance_evidence%','Intake captures provenance and evidence');
select ok(pg_temp.normalized_functiondef('erp.review_trade_in_provenance(uuid,erp.trade_in_review_decision,text)') like '%identity%ownership%','Provenance approval requires identity or ownership evidence');
select ok(pg_temp.normalized_functiondef('erp.request_trade_in_imei_check(uuid,text,text,text)') like '%pgp_sym_encrypt%','Provider request encrypts IMEI');
select ok(pg_temp.normalized_functiondef('erp.record_trade_in_imei_provider_result(uuid,erp.imei_check_status,text,jsonb,text)') like '%fromerp.trade_ins%forupdate%','Provider result serializes on the trade-in');
select ok(pg_temp.normalized_functiondef('erp.record_trade_in_imei_provider_result(uuid,erp.imei_check_status,text,jsonb,text)') like '%providerrequestalreadyhasadifferentresult%','Provider result retry is strongly compared');
select ok(pg_temp.normalized_functiondef('erp.record_trade_in_imei_manual_fallback(uuid,erp.imei_check_status,jsonb,text,text)') like '%latestproviderrequestmustendunavailableorerror%','Manual fallback is tied to the latest failed request');
select ok(pg_temp.normalized_functiondef('erp.record_trade_in_imei_manual_fallback(uuid,erp.imei_check_status,jsonb,text,text)') like '%fallback_status=''not_required''andhas_imei%','Not-required is limited to no-IMEI units');
select ok(pg_temp.normalized_functiondef('erp.release_trade_in_to_stock(uuid,uuid,text,text)') like '%orderbyrequest_versiondesclimit1%','Release evaluates the highest IMEI request version');
select ok(pg_temp.normalized_functiondef('erp.release_trade_in_to_stock(uuid,uuid,text,text)') like '%latestprovenancereviewmustapproverelease%','Release gates latest provenance');
select ok(pg_temp.normalized_functiondef('erp.release_trade_in_to_stock(uuid,uuid,text,text)') like '%latestevaluationmustbeapproved%','Release gates latest evaluation');
select ok(pg_temp.normalized_functiondef('erp.release_trade_in_to_stock(uuid,uuid,text,text)') like '%allrefurbishmentworkmustbecompleted%','Release gates refurbishment completion');
select ok(pg_temp.normalized_functiondef('erp.release_trade_in_to_stock(uuid,uuid,text,text)') like '%total:=evaluation.appraised_value_base+refurb%','Release computes appraisal plus refurbishment cost');
select ok(pg_temp.normalized_functiondef('erp.release_trade_in_to_stock(uuid,uuid,text,text)') like '%post_stock_document_core%''trade_in''%' and pg_temp.normalized_functiondef('erp.release_trade_in_to_stock(uuid,uuid,text,text)') like '%process_stock_document_costs%','Approved release posts physical stock and valuation through hidden cores');
select ok(pg_temp.normalized_functiondef('erp.post_stock_document(erp.stock_document_kind,uuid,text,text,jsonb,boolean,text,uuid)') like '%trade-inquarantineadmissionrequiresapprovedreleasecommand%','Generic stock admission has a hard quarantine gate');
select ok(pg_temp.normalized_functiondef('erp.reverse_stock_document(uuid,text,text)') like '%trade-inreleasesrequireadedicatedcompensatingworkflow%','Generic stock reversal cannot orphan a release fact');
select ok(pg_temp.normalized_functiondef('erp.apply_trade_in_sale_payment(uuid,uuid,numeric,text,text)') like '%fromerp.trade_ins%forupdate%','Trade-in payment serializes on the trade-in');
select ok(pg_temp.normalized_functiondef('erp.apply_trade_in_sale_payment(uuid,uuid,numeric,text,text)') like '%claim_stage7_command%','Trade-in payment is request-idempotent');
select ok(pg_temp.normalized_functiondef('erp.reverse_sale_payment(uuid,text,text,uuid)') like '%trade-inpaymentsrequirereverse_trade_in_sale_payment%','Generic payment reversal cannot orphan trade-in facts');
select ok(pg_temp.normalized_functiondef('erp.reverse_trade_in_sale_payment(uuid,text,text)') like '%reverse_sale_payment_stage7_core%','Dedicated trade-in reversal uses the private payment core');
select ok(exists(select 1 from pg_trigger where tgrelid='erp.trade_in_releases'::regclass and tgname='trade_in_releases_relationship'),'Release facts validate stock ownership');
select ok(exists(select 1 from pg_trigger where tgrelid='erp.trade_in_sale_payment_events'::regclass and tgname='trade_in_payment_relationship'),'Trade-in payment facts validate payment ownership');
select ok(pg_temp.normalized_functiondef('erp.audit_stage7_fact()') like '%''redacted'',true%','Stage 7 audit payloads are redacted');
select ok(pg_temp.normalized_functiondef('erp.claim_stage7_command(text,uuid,uuid,text,jsonb)') like '%sha256%','Stage 7 commands use SHA-256');
select ok(pg_temp.normalized_functiondef('erp.claim_stage7_command(text,uuid,uuid,text,jsonb)') like '%pg_advisory_xact_lock%','Stage 7 command claims serialize retries');

-- Deterministic seed and role matrices.
select is((select count(*) from erp.locations where id='30000000-0000-0000-0000-000000000008' and code='CUARENTENA-CANJES' and not allows_sale and not contributes_to_web_stock),1::bigint,'Quarantine location is seeded safely');
select is((select count(*) from erp.payment_methods where id='82000000-0000-0000-0000-000000000004' and code='TRADE_IN' and settlement_kind='credit' and not requires_cash_session and is_active),1::bigint,'Non-cash trade-in payment is seeded');
select is((select count(*) from erp.pc_compatibility_specs where id='86000000-0000-0000-0000-000000000001' and is_active),1::bigint,'PC compatibility spec is seeded');
select is((select count(*) from erp.pc_compatibility_spec_versions where id='86300000-0000-0000-0000-000000000001' and version=1),1::bigint,'PC spec version is seeded');
select is((select count(*) from erp.pc_compatibility_rule_sets where id='86100000-0000-0000-0000-000000000001' and is_active),1::bigint,'PC rule set is seeded');
select is((select count(*) from erp.pc_compatibility_rule_set_versions where id='86400000-0000-0000-0000-000000000001' and version=1),1::bigint,'PC rule-set version is seeded');
select is((select count(*) from erp.pc_compatibility_rules where rule_set_version_id='86400000-0000-0000-0000-000000000001'),3::bigint,'Three standard compatibility rules are seeded');
select is((select count(*) from erp.pc_test_templates where id='86200000-0000-0000-0000-000000000001' and is_active),1::bigint,'PC final test template is seeded');
select is((select count(*) from erp.pc_test_template_versions where id='86600000-0000-0000-0000-000000000001' and version=1),1::bigint,'PC final test version is seeded');
select is((select jsonb_array_length(definition) from erp.pc_test_template_versions where id='86600000-0000-0000-0000-000000000001'),4,'PC final test has four required checks');
select is((select count(*) from erp.permissions where code='trade_ins.approve' and is_sensitive and is_active),1::bigint,'Trade-in approval permission is sensitive');
select is((select count(*) from erp.role_permissions rp join erp.permissions p on p.id=rp.permission_id where rp.role_id='40000000-0000-0000-0000-000000000001' and p.code='trade_ins.approve' and rp.is_active),1::bigint,'Owner receives trade-in approval');
select is((select count(*) from erp.role_permissions rp join erp.permissions p on p.id=rp.permission_id where rp.role_id='40000000-0000-0000-0000-000000000003' and p.code='trade_ins.approve' and rp.is_active),0::bigint,'Technician does not receive trade-in approval');
select is((select count(*) from erp.role_permissions rp join erp.permissions p on p.id=rp.permission_id where rp.role_id='40000000-0000-0000-0000-000000000004' and p.code='trade_ins.approve' and rp.is_active),0::bigint,'Inventory does not receive trade-in approval');
select is((select count(*) from erp.role_permissions rp join erp.permissions p on p.id=rp.permission_id where rp.role_id='40000000-0000-0000-0000-000000000003' and p.code='pc_builds.manage' and rp.is_active),1::bigint,'Technician can manage PC builds');
select is((select count(*) from erp.role_permissions rp join erp.permissions p on p.id=rp.permission_id where rp.role_id='40000000-0000-0000-0000-000000000004' and p.code='trade_ins.manage' and rp.is_active),1::bigint,'Inventory can manage trade-in intake');
select is((select count(*) from erp.role_permissions rp join erp.permissions p on p.id=rp.permission_id where rp.role_id='40000000-0000-0000-0000-000000000002' and p.code='trade_ins.view' and rp.is_active),1::bigint,'Sales can view trade-ins without management rights');
select is((select count(*) from erp.configuration_values where organization_id='10000000-0000-0000-0000-000000000001' and key='pc_builds.default_spec_version'),1::bigint,'Default PC spec configuration is seeded');
select is((select count(*) from erp.configuration_values where organization_id='10000000-0000-0000-0000-000000000001' and key='pc_builds.default_rule_set_version'),1::bigint,'Default PC rules configuration is seeded');
select is((select value#>>'{}' from erp.configuration_values where organization_id='10000000-0000-0000-0000-000000000001' and branch_id is null and key='pc_builds.final_test_template_version'),'86600000-0000-0000-0000-000000000001','Final PC test template is pinned deterministically');
select is((select count(*) from erp.configuration_values where organization_id='10000000-0000-0000-0000-000000000001' and key='trade_ins.imei_manual_fallback'),1::bigint,'Manual fallback policy is seeded');

select * from finish();
rollback;
